### ISSUE TITLE
代码架构

### ISSUE THREAD

**Issue by Rratic** [1P-Studio-Offical/Survive#1]
简单说一下C++工程结构
源代码文件主要分三类
- 主文件，一般命名为main.cpp
- 头文件x.h
- 对于的实现文件x.cpp，名字一般与所实现的头文件相同

建议使用命令行编译（好加参数）
例如
src/
main.cpp
123.h
123.cpp
使用指令`gcc src/main.cpp src/123.cpp -o src/progress.exe`编译

**Comment by Rratic** [comment]
继续说
头文件主要是函数、类的定义，如果需要定义全局变量，需加上`extern`
一个例子
123.h:
```cpp
#ifndef 123_h
#define 123_h
#include<iostream>
extern bool s;
void hw();
#endif
```
123.cpp:
```cpp
#include"123.h"
void hw(){
if(s)cout<<"HELLO";
cout<<"WORLD";
}
```
main.cpp
```cpp
#include"123.h"
int main(){
hw();
return 0;
}
```

**Comment by 1P-Studio-Offical** [comment]
Thanks for helping a github green-hand,we have changed the 1.3.5 version into this type
感谢，@Rratic

**Comment by Rratic** [comment]
@1P-Studio-Offical 
> we have changed the 1.3.5 version into this type

Sorry,but,am I blind or you failed to realize that the only place you placed the structure is your `release`,instead of pushing a new update and **then** publish a release.

**Comment by Rratic** [comment]
~~我还是正常一点~~
工程结构的目的是为了方便更新，
如果想快速压缩成一个文件，可以试试我的[OneFile工具](https://github.com/Rratic/OneFile)
